version: "3.8"

services:
  frontend:
    image: easypanel/test/hospital-project-front:latest
    ports:
      - "3001:3001"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
